name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: create env file
        run: |
          touch .env
          echo VITE_API_KEY=${{ secrets.VITE_API_KEY }} >> .env
          echo VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }} >> .env
          echo VITE_DATABSE_URL=${{ secrets.VITE_DATABSE_URL }} >> .env
          echo VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }} >> .env
          echo VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }} >> .env
          echo VITE_MESSAGIN_SENDER_ID=${{ secrets.VITE_MESSAGIN_SENDER_ID }} >> .env
          echo VITE_APP_ID=${{ secrets.VITE_APP_ID }} >> .env
          echo VITE_MEASUREMENT_ID=${{ secrets.VITE_MEASUREMENT_ID }} >> .env
          cat .env

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch origin
          git reset --hard origin/gh-pages
          find . -mindepth 1 -maxdepth 1 ! -name 'build' ! -name '.git' ! -name 'build' -exec rm -rf {} +
          mv -fv build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin HEAD:gh-pages || true
